### ISSUE TITLE
Could you give more instructions for running your code?

### ISSUE THREAD

**Issue by ZhuPeipei-CUHKSZ-TJUTCM** [baldassarreFe/ws-vrd#4]
Thanks for sharing your code! You share us with the data preparation and pre-processing. Could you share more instructions for running the /xib/train.py and testing the predicate classification model? Like the following:

python -m xib.preprocessing.vrd \
  --confidence-threshold=.3 \
  --d2-dir="models/detectron_vrd_train" \
  --data-dir="./data" \
  --output-dir="data/vrd/processed"

Thanks a lot.

**Comment by baldassarreFe** [comment]
Hi, the documentation at the moment is very scarce, sorry. I'm working on it and I'll put all instructions in the README.

In general, training configurations are parsed from yaml files, just like the one at https://github.com/baldassarreFe/ws-vrd/blob/master/config/train.yaml

Then you launch the job as:
```bash
python -m xib.train path/to/config.yaml
```

The config parser is actually quite flexible, it even allows something like this
```bash
python -m xib.train config1.yaml config2.yaml session.max_epochs=35
```

**Comment by username123062** [comment]
> Hi, the documentation at the moment is very scarce, sorry. I'm working on it and I'll put all instructions in the README.
> 
> In general, training configurations are parsed from yaml files, just like the one at https://github.com/baldassarreFe/ws-vrd/blob/master/config/train.yaml
> 
> Then you launch the job as:
> 
> ```shell
> python -m xib.train path/to/config.yaml
> ```
> 
> The config parser is actually quite flexible, it even allows something like this
> 
> ```shell
> python -m xib.train config1.yaml config2.yaml session.max_epochs=35
> ```

Thanks for your attention! I ran your code by:

python -m xib.train /userhome/code/zhupp_unpaired_image_captioning/code/ws-vrd-master/config/visual_relations_vrd.yaml /userhome/code/zhupp_unpaired_image_captioning/code/ws-vrd-master/config/visual_relations_hico.yaml session.max_epochs=35 

But, got the following errors, so could you help me again?
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
Traceback (most recent call last):
  File "/usr/local/python-3.7.5/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/python-3.7.5/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/userhome/code/zhupp_unpaired_image_captioning/code/ws-vrd-master/src/xib/train.py", line 981, in <module>
    main()
  File "/usr/local/python-3.7.5/lib/python3.7/site-packages/loguru/_logger.py", line 1220, in catch_wrapper
    return function(*args, **kwargs)
  File "/userhome/code/zhupp_unpaired_image_captioning/code/ws-vrd-master/src/xib/train.py", line 425, in main
    setup_seeds(conf.session.seed)
  File "/userhome/code/zhupp_unpaired_image_captioning/code/ws-vrd-master/src/xib/train.py", line 67, in setup_seeds
    torch.manual_seed(seed)
  File "/usr/local/python-3.7.5/lib/python3.7/site-packages/torch/random.py", line 28, in manual_seed
    seed = int(seed)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

**Comment by username123062** [comment]
> Hi, the documentation at the moment is very scarce, sorry. I'm working on it and I'll put all instructions in the README.
> 
> In general, training configurations are parsed from yaml files, just like the one at https://github.com/baldassarreFe/ws-vrd/blob/master/config/train.yaml
> 
> Then you launch the job as:
> 
> ```shell
> python -m xib.train path/to/config.yaml
> ```
> 
> The config parser is actually quite flexible, it even allows something like this
> 
> ```shell
> python -m xib.train config1.yaml config2.yaml session.max_epochs=35
> ```

**1. Thanks for your reply! I have run your code as follows:**

python -m xib.train ws-vrd-master/config/train.yaml session.max_epochs=35

**But gotten the following error:**
-------------------------------------------------------------
AttributeError: 'NoneType' object has no attribute 'name'
Traceback (most recent call last):
  File "/usr/local/python-3.7.5/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/python-3.7.5/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/ws-vrd-master/xib/train.py", line 983, in <module>
    main()
  File "/usr/local/python-3.7.5/lib/python3.7/site-packages/loguru/_logger.py", line 1220, in catch_wrapper
    return function(*args, **kwargs)
  File "/ws-vrd-master/xib/train.py", line 440, in main
    model = build_model(conf.model, dataset_metadata["train_gt"]).to(
  File "/ws-vrd-master/xib/train.py", line 354, in build_model
    model_fn: Callable[[OmegaConf, Metadata], torch.nn.Module] = import_(conf.name)
AttributeError: 'NoneType' object has no attribute 'name'


**2. Also, when I ran "python -m xib.train /ws-vrd-master/config/visual_relations_vrd.yaml", I got the following error:**

---------------------------------------------------------------------
AttributeError: 'NoneType' object has no attribute 'seed'
Traceback (most recent call last):
  File "/usr/local/python-3.7.5/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/python-3.7.5/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/userhome/code/zhupp_unpaired_image_captioning/code/ws-vrd-master/xib/train.py", line 983, in <module>
    main()
  File "/usr/local/python-3.7.5/lib/python3.7/site-packages/loguru/_logger.py", line 1220, in catch_wrapper
    return function(*args, **kwargs)
  File "/userhome/code/zhupp_unpaired_image_captioning/code/ws-vrd-master/xib/train.py", line 427, in main
    setup_seeds(conf.session.seed)
AttributeError: 'NoneType' object has no attribute 'seed'

**Could you help me again? Thanks a lot.**

**Comment by ZhuPeipei-CUHKSZ-TJUTCM** [comment]
Thanks a lot!
